# Generated by Django 5.1.15 on 2026-01-28 15:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(unique=True)),
                ('reward_type', models.CharField(default='coins', max_length=20)),
                ('reward_amount', models.IntegerField()),
                ('is_special', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('task_type', models.CharField(choices=[('clicks', 'Total Clicks'), ('upgrades', 'Upgrades Purchased'), ('referrals', 'Referrals'), ('level', 'Reach Level'), ('balance', 'Balance Target')], max_length=20)),
                ('target_value', models.IntegerField()),
                ('reward_coins', models.IntegerField()),
                ('reward_energy', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Upgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('base_cost', models.IntegerField()),
                ('cost_multiplier', models.FloatField(default=1.15)),
                ('upgrade_type', models.CharField(choices=[('coins_per_click', 'Coins Per Click'), ('max_energy', 'Max Energy'), ('energy_regen', 'Energy Regeneration'), ('multiplier', 'Coin Multiplier')], max_length=20)),
                ('base_effect_value', models.IntegerField()),
                ('effect_per_level', models.IntegerField()),
                ('max_level', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('balance', models.BigIntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('energy', models.IntegerField(default=1000)),
                ('max_energy', models.IntegerField(default=1000)),
                ('energy_regen_rate', models.IntegerField(default=1)),
                ('coins_per_click', models.IntegerField(default=1)),
                ('last_energy_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerDailyReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_consecutive', models.BooleanField(default=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clicker_app.player')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clicker_app.dailyreward')),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reward_claimed', models.BooleanField(default=False)),
                ('referred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to='clicker_app.player')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='clicker_app.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clicker_app.player')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clicker_app.task')),
            ],
            options={
                'unique_together': {('player', 'task')},
            },
        ),
        migrations.CreateModel(
            name='PlayerUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('purchased_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clicker_app.player')),
                ('upgrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clicker_app.upgrade')),
            ],
            options={
                'unique_together': {('player', 'upgrade')},
            },
        ),
    ]
